### ISSUE TITLE
[BUG] Error on NPC Ability scores

### ISSUE THREAD

**Issue by Carciphona23** [Larkinabout/fvtt-custom-dnd5e#104]
**Describe the bug**

There's seems to be a visual bug upon updating to version 1.0.0 with all other modules disabled other than itself disabled.
![Screenshot 2024-09-18 212019](https://github.com/user-attachments/assets/cde5203d-e179-42cc-936d-c2268d19ab17)

**Versions:**
- Module: 1.0.0
- System: dnd5e 4.0.2
- Foundry VTT: [e.g. 12.331]

**Additional context**
Any additional context.

**Comment by pwykersotz** [comment]
This also happens in spells. They look fine, but once cast, the character sheet changes.
![image](https://github.com/user-attachments/assets/10e342c0-77c2-4ea0-bdb6-a3eddfcc2323)

**Comment by Larkinabout** [comment]
It looks like the non-localized string is being saved to settings. Until I release a fix, you should be able to rectify it yourself by going into the configuration under **Game Settings** > **Configure Settings** > **Custom D&D 5e** > **Configure ...** and clicking **Save and Close**.

**Comment by Larkinabout** [comment]
Fixed in 1.0.1.
