### ISSUE TITLE
[BUG] Cannot open Configure Spell School after saving the setting without filling the reference while adding a new school

### ISSUE THREAD

**Issue by FreezinPenguin** [Larkinabout/fvtt-custom-dnd5e#105]
**Describe the bug**

When configuring a spell school, I accidentally saved and closed the setting while still adding a new spell school that is still missing reference (abbreviation, name, icons are all done, but haven't added any reference) and now I cannot open the Configure Spell Schools anymore.

This is the error from the browser console after clicking on the 'Configure Spell School'
![customdnd5e configurespellschool error](https://github.com/user-attachments/assets/ea7c7f8a-a0d8-4093-88c5-2c9cc3fb958d)

**Module Data**

Go into the module's settings, open up the Debug Settings menu, click Export Data, save and attach the file here.

**Steps to reproduce**
1. Go to 'Custom D&D 5e'
2. Click on 'Configure Spell Schools'
3. Create a new spell school and fill out all the forms except reference
4. Scroll down to 'Save and close'
5. Try to open 'Configure Spell Schools' again

**Versions:**
- Module: 1.0.1
- System: 3.3.1 and 4.0.2
- Foundry VTT: Version 12 Stable - Build 331
- Browser: MicrosoftEdge

**Comment by Larkinabout** [comment]
Can you attach your debug file please. There's a bug with the Spell Schools config that I'll fix with the next release, but I'll need to modify your debug file, so you can re-import it after you've updated.

**Comment by FreezinPenguin** [comment]
Gladly, will you be able to guide me on how to get the debug file? As I don't know where those are located.

**Comment by Larkinabout** [comment]
Certainly, go to **Configure Settings** > **Custom D&D 5e**. Scroll down to **Debug Settings** and open it. Click **Export Data**.

**Comment by FreezinPenguin** [comment]
[custom-dnd5e.json](https://github.com/user-attachments/files/17092429/custom-dnd5e.json)

Hello! Sorry it took quite a while to get back to you. Here is the debug setting (DnD version is now 4.0.2 if that matters. Please let me know if I should revert back and give you the debug file for 3.3.1 instead).

**Comment by Larkinabout** [comment]
Here you go, import this using the **Import Data** option in the **Debug Settings** window: [custom-dnd5e-FreezinPenguin.json](https://github.com/user-attachments/files/17093490/custom-dnd5e-FreezinPenguin.json)

**Comment by FreezinPenguin** [comment]
I'm so sorry I totally forgot about this issue, but to update, yes it is fixed now! And thank you very much!
