### ISSUE TITLE
[BUG] Reference does not pull text from Journal Entries

### ISSUE THREAD

**Issue by GaelusTV** [Larkinabout/fvtt-custom-dnd5e#108]
**Describe the bug**
Reference text does not show up on the character sheet when skills or conditions are hovered over, instead only showing an infinite loading circle.
![1](https://github.com/user-attachments/assets/72bdce45-dcbd-4b62-83a9-2b0c1ec5c9e5)
_How it looks_

![2](https://github.com/user-attachments/assets/7ab5f9e6-c729-4aba-828e-56431c242f75)
_How it should look_

![3](https://github.com/user-attachments/assets/baec8ead-a34e-42ea-aa63-ca55784b083b)
_How it looks_

![4](https://github.com/user-attachments/assets/b6715cd4-7daa-4d8e-b1ef-c4a00dba7b1e)
_How it should look_

![5](https://github.com/user-attachments/assets/1a77c93b-f0f5-4c86-9320-d499b9dd37b9)
_How the settings look, the reference is tied to a journal entry for my compendium. I have tried changing where it pulls the reference from with no change_

**Module Data**
[custom-dnd5e.json](https://github.com/user-attachments/files/17065236/custom-dnd5e.json)

**Steps to reproduce**
1. Create a Skill / Condition
2. Configure Skill / Condition with a reference UUID and enable Sheet
3. Hover over the new Skill / Condition on a character sheet

**Versions:**
- Module: 1.0.3
- System: dnd5e 4.0.2
- Foundry VTT: Version 12 Stable, Build 331
- Browser: Google Chrome 128

**Comment by Larkinabout** [comment]
Ah, yes, you have to put the content of the tooltip in the Tooltip section of a Rule journal. I'll add guidance to the Custom D&D 5e journal as it took me a while to figure out where it needed to go.
![image](https://github.com/user-attachments/assets/f6eae634-e62e-42d4-be1d-ce809dff58cb)

**Comment by GaelusTV** [comment]
That worked wonders! Thanks for the quick reply, and for the fantastic module!
