### ISSUE TITLE
[BUG] 4.0 System Exhaustion Effects not working

### ISSUE THREAD

**Issue by ctbritt** [Larkinabout/fvtt-custom-dnd5e#109]
**Describe the bug**
When applying exhaustion on the char sheet in 2024 D&D 4.0.2 while Custom D&D 5e is enabled, there is no exhaustion penalty applied.

**Module Data**
[Custom DND5E.json](https://github.com/user-attachments/files/17067507/Custom.DND5E.json)

**Steps to reproduce**
1. Enable Custom D&D 5e module
2. Open Char sheet and apply exhaustion via the pips
3. Make a D20 check. 

**Versions:**
- Module: 1.0.3
- System: dnd5e 4.0.2
- Foundry VTT: 12.331
- Browser: Chromium 128.0.6613.138

**Additional context**
With Custom 5e enabled (with 3 levels of exhaustion): 
![CleanShot 2024-09-19 at 18 32 46](https://github.com/user-attachments/assets/8dcde490-3dbf-4588-b1df-13424deafa9e) 

With Custom 5e disabled (with 3 levels of exhaustion):
![CleanShot 2024-09-19 at 18 35 38](https://github.com/user-attachments/assets/8c1a172f-523f-46de-885e-fcafa995039e)

This happens even when Custom 5e is the only module enabled.

**Comment by Larkinabout** [comment]
Thanks, I'd missed the new `reduction` properties. I usually merge in the core config in case there's any new additions, but I hadn't done it for conditions. I've also added the properties to the Exhaustion condition item in Configure Conditions, so you can change them as desired.

Fixed in 1.0.4.

![image](https://github.com/user-attachments/assets/7e1401f7-6638-4983-a6b9-8afbfd30f1ad)

**Comment by matikheit** [comment]
**Describe the bug**
Using Custom D&D 5e it happened to me that when I added our weapon properties to the system, then it did not allow me to edit any object that was considered a weapon. I could edit backgrounds, classes and even trinkets, but when I try to open a weapon, I don't get the screen to read its description or edit it. When I deactivate the module, then I can open it.

**Versions:**
- Module: 1.0.4
- System: dnd5e 4.0.2
- Foundry VTT: 12.331

**Comment by Larkinabout** [comment]
This is a different issue. Please create a new issue and make sure to include your debug file from Custom D&D 5e.

**Comment by matikheit** [comment]
I just don't know how to do it, because I don't know what a debug file is :(

**Comment by Larkinabout** [comment]
Create a new Bug issue and it will tell you how to get the file. It's the **Module Data** part of the issue.
