### ISSUE TITLE
[BUG] Custom DnD doesn't play nicely with 5e Sheet Resources Plush

### ISSUE THREAD

**Issue by Opius134** [Larkinabout/fvtt-custom-dnd5e#111]
When Custom DnD5e (1.0.4) is enabled,[ 5e sheet resources plus ](https://github.com/ardittristan/5eSheet-resourcesPlus) doesn't work as expected. 
![image](https://github.com/user-attachments/assets/ada3e833-8395-4235-a68b-550f9e9a4d11)

The module _should_ allow me to change the number of resources on a sheet. This affects both the tidy sheet and 5e classic sheet. 

**Module Data**
Custom DnD5e (1.0.4) with Sheet Resources Plus 1.10.1, foundry version 12.331. DnD 3.3.1

It seems this behavior began with Custom DnD v. 1.0.0

**Comment by Larkinabout** [comment]
This doesn't look like a bug related to Custom D&D 5e. I've tested on both dnd5e 3.3.1 and 4.0.2 with the latest releases of Tidy sheets and 5e- Sheet Resources Plus and they have interacted okay with Custom D&D 5e 1.0.4.
![image](https://github.com/user-attachments/assets/ad814c8a-8534-4bde-a99d-af8227657f21)
![image](https://github.com/user-attachments/assets/2c3e6a8c-866f-4924-8e95-9c2f930680c1)

**Comment by Opius134** [comment]
ty for the update, I'll look into my configuration!
