### ISSUE TITLE
[BUG]"Apply Instant Death" House Rule removes Custom Abilities and Skills from Sheet

### ISSUE THREAD

**Issue by Cheesysteaks** [Larkinabout/fvtt-custom-dnd5e#115]
Describe the bug

The House Rule "Apply Instant Death" Removes Custom Abilities and Skills from the character sheet. The custom ability/skills can still be called by other items and features, they just don't show up on the sheet while the instant death rule is enabled. This issue has persisted since the last update and I thought it had to do with 5e updating, until I tested it in a new game world.

**Versions:**
- Module: [1.0.5]
- System: [dnd5e 4.0.3 ]
- Foundry VTT: [12.331]
- Browser: [Desktop App]

**Additional context**
No other modules are enabled.

**Comment by Larkinabout** [comment]
Fixed in 1.0.6.
