### ISSUE TITLE
[BUG] House Rules > Apply Bloodied Condition Not Working

### ISSUE THREAD

**Issue by LovelessLucidity** [Larkinabout/fvtt-custom-dnd5e#119]
**Describe the bug**

When an actor goes below 50% HP the custom bloodied condition does not apply. Console gives this:

![image](https://github.com/user-attachments/assets/92b6f4b4-3cf8-49f5-b612-e6457290451d)

I've run the module solo with same results. I then unticked the option to apply bloodied and then turned the D&D5e bloodied option back on, this resulted in the default bloodied icon/status to be applied, but the token tint turned red even though it was unticked in the Custom-dnd5e settings. This notification then displayed:

![image](https://github.com/user-attachments/assets/5426c664-3465-4a58-adb5-cc059c5f770c)

Resetting the HP to max (tint returned to default with this) then gave this notification:

![image](https://github.com/user-attachments/assets/253d39f6-2773-4603-b37d-f8f76dadcebd)

**Module Data**

Go into the module's settings, open up the Debug Settings menu, click Export Data, save and attach the file here.

[custom-dnd5e.json](https://github.com/user-attachments/files/17231793/custom-dnd5e.json)

**Steps to reproduce**
1. Go to GAME SETTINGS > CONFIGURE SETTINGS > CUSTOM D&D 5e > CONFIGURE HOUSE RULES
2. Tick APPLY BLOODIED > SAVE
3. Change HP of an actor on the canvas to below 50%

**Versions:**
- Module: 1.1.0
- System: dnd5e 4.0.4
- Foundry VTT: 12.331
- Browser: Google Chrome Version 129.0.6668.71

**Additional Context**

Be gentle if it's a straight up User error on my part

**Comment by Larkinabout** [comment]
Hopefully fixed with 1.1.1, however I couldn't get it to fail on my side, so if you can update and let me know if it's resolved please.

**Comment by LovelessLucidity** [comment]
Installed new update and the issue has resolved! This is such a great mod - Thank you for this
