### ISSUE TITLE
[FEATURE] Different Dice for Initiative

### ISSUE THREAD

**Issue by maxobremer** [Larkinabout/fvtt-custom-dnd5e#120]
**Describe your idea**
It could be cool to have different dice be used for stuff like initiative. Baldur's Gate 3 for example uses a d4 which makes features like alert and having a higher dex much more impactfull.
If you could choose which doce to be used then game masters can decide for themselves which one feels nice for their table. 
An extension though maybe a bit too mayor one would be to allow all d20 tests to be adjusted to use a smaller or larger dice.

**Additional context**
Good work on the module so far

**Comment by Larkinabout** [comment]
This'll require changes to the dnd5e system, otherwise it's a bunch of patching to make it work. I'll raise a pull request over there to see if I can get the required changes accepted. It's not too much, so hopefully it will.

**Comment by Larkinabout** [comment]
https://github.com/foundryvtt/dnd5e/pull/4514

**Comment by Larkinabout** [comment]
Added in 1.2.0.
