### ISSUE TITLE
[BUG] Module ignoring settings

### ISSUE THREAD

**Issue by Stonedtroll** [Larkinabout/fvtt-custom-dnd5e#121]
**Describe the bug**

Even though the Applied Bloodied option is unchecked, the module still try to apply the condition. 

On damage:

![image](https://github.com/user-attachments/assets/53f945be-dd6b-4424-8361-766f90c3f9bd)

On heal:

![image](https://github.com/user-attachments/assets/ba362531-87a1-4dcd-9160-2a747044a3d1)

**Steps to reproduce**
1. Go to Configure House Rules
2. Make sure the Apply Bloodied checkbox is uncheck
3. Apply damage to a character

**Versions:**
- Module: 1.1.1
- System: dnd5e 4.0.4
- Foundry VTT: 12.331
- Browser: Google Chrome

**Comment by Larkinabout** [comment]
Related to https://github.com/foundryvtt/dnd5e/issues/4485

**Comment by Larkinabout** [comment]
Resolved with dnd5e 4.1+.
