### ISSUE TITLE
[FEATURE] Don't shuffle condition orders from base game by default

### ISSUE THREAD

**Issue by Krigsmaskine** [Larkinabout/fvtt-custom-dnd5e#122]
**Describe your idea**
Even without utilizing Custom Conditions, I noticed it shuffles them around in the token hud. I think it just lists them alphabetically, whereas the standard dnd5e lists them from most used. It'd be nice if it kept the original order until changed and it also clears up some confusion for people using the module, as it's unexpected to have changes to the conditions without "opting in" to the changes in custom 5e like the rest of the settings. Here's the standard arrangement, the module puts Bleeding first, a rare condition, so it should be immediately noticeable the module interjects. 
![image](https://github.com/user-attachments/assets/46f21de7-f755-476a-ad0e-f8d759224038)

**Versions**
- Module: 1.0.4
- System: 4.0.4
- Foundry VTT: 12.331

edit: a worthy note that "reset to default" then in this case only refers to custom 5e default, as the order is still changed when resetting

**Comment by Larkinabout** [comment]
Fixed in 1.1.2. You will need to go into **Configure Conditions** and click **Reset to Default**.
