### ISSUE TITLE
[BUG] Unchecking the "Include on Sheet" prevents the character sheet from opening

### ISSUE THREAD

**Issue by Stonedtroll** [Larkinabout/fvtt-custom-dnd5e#125]
**Describe the bug**

Unchecking the "Include on Sheet" prevents the character sheet from opening

![Screenshot 2024-10-13 at 12 32 51 pm](https://github.com/user-attachments/assets/3d81266c-5980-4e55-a036-02bed528ae8a)

**Steps to reproduce**
1. Go to the Configure Conditions > Exhaustion option 
2. Uncheck the Include on Sheet
3. Save
4. Double click on a token to open the character sheet

**Versions:**
- Module: 1.1.2
- System: D&D5e 4.0.4
- Foundry VTT: 12.331
- Browser: Google Chrome

**Comment by Larkinabout** [comment]
There is an issue with removing the core exhaustion condition currently. I have a pull request open over on the dnd5e github, which should be accepted for the next dnd5e release.

**Comment by Larkinabout** [comment]
https://github.com/foundryvtt/dnd5e/pull/4338

**Comment by Larkinabout** [comment]
Resolved with dnd5e 4.1+.
