### ISSUE TITLE
[BUG] Uninstalling module does not reset the system to previous state

### ISSUE THREAD

**Issue by Stonedtroll** [Larkinabout/fvtt-custom-dnd5e#126]
**Describe the bug**

Uninstalling module does not reset the system to previous state. e.g. 

- Conditions changes remain. 
- Settings were recovered after reinstalling. 

**Versions:**
- Module: 1.1.2
- System: D&D5e 4.0.4
- Foundry VTT: 12.331
- Browser: Google Chrome

**Comment by Larkinabout** [comment]
Can you let me know what you mean by condition changes remain once the module is disabled. The module sets the config, which if you disable the module, will revert back to the system config. Are you getting an error after disabling the module?

**Comment by Stonedtroll** [comment]
I am still getting issue #127 even after uninstalling the module.

**Comment by Larkinabout** [comment]
Fixed in 1.2.0.
