### ISSUE TITLE
[BUG] Encumbrance lost its correct label

### ISSUE THREAD

**Issue by Stonedtroll** [Larkinabout/fvtt-custom-dnd5e#127]
**Describe the bug**

 Encumbrance label no longer display correctly

![Screenshot 2024-10-13 at 12 26 50 pm](https://github.com/user-attachments/assets/89227c61-f4f1-4f63-a790-0318657e3884)

**Versions:**
- Module: 1.1.2
- System: D&D5e 4.0.4
- Foundry VTT: 12.331
- Browser: Google Chrome

**Comment by Stonedtroll** [comment]
I created a fresh world with just the following modules:

![image](https://github.com/user-attachments/assets/f623efc7-2cb0-4493-b1f3-b5ea14080f39)

Go to Configure Conditions, make no changes, and save. This issue will appear.

**Comment by Larkinabout** [comment]
Fixed in 1.2.0.
