### ISSUE TITLE
[BUG] Bloodied effect oddities

### ISSUE THREAD

**Issue by Krigsmaskine** [Larkinabout/fvtt-custom-dnd5e#129]
**Describe the bug**

Even without having the House Rule version of Bloodied on, having Custom 5e on makes oddities happen with the core system's implementation. I think it's actually a biproduct of the "apply status effect to selected", but these are the easiest repro steps for some of the issues I've experienced.

**Module Data**
[custom-dnd5e.json](https://github.com/user-attachments/files/17369623/custom-dnd5e.json)

**Steps to reproduce**
1. Have Bloodied house rules off, but core Bloodied on.
2. Select more than 1 token.
3. Adjust 1 of the tokens to below 50%, see Bloodied get added.
4. Adjust the same token to above 50%, see Bloodied get removed, but an error prompted.

**Versions:**
- Module: 1.1.2
- System: dnd5e 4.0.4
- Foundry VTT: 12.331
- Browser: Foundry

**Additional context**
I have noticed other ActiveEffect oddities with Custom 5e enabled and I believe they're rooted in the same issue, but this is the one I can repro consistently. Stuff like trying to remove ActiveEffects already removed, trying to add ActiveEffects already added. It seems to happen with the core's system Bloodied consistently. I would just swap to the Custom 5e one, but it seems to have this attached to it's tooltip and I have been unable to find out how to change it 
![image](https://github.com/user-attachments/assets/2285721c-86e4-417a-96fc-a7423901cc54)

**Comment by Larkinabout** [comment]
The Bloodied error is specifically due to this: https://github.com/foundryvtt/dnd5e/issues/4485 — currently it'll happen for any module that makes an actor update as part of the `updateActor` hook.

**Comment by Krigsmaskine** [comment]
The long description is in both available effect panel modules and it's looks to me that it's because the Bloodied activeEffect by Custom 5e populates its `description` with that journal entry. It doesn't seem like the standard status effects have this property populated, so maybe it's unneeded? It did make me realize I can fix having most of the contents in there by just editing the journal entry it links to, though.

Bloodied activeEffect
![image](https://github.com/user-attachments/assets/ad0d64b4-57e1-42ad-b8e7-a9d27f96741f)

Charmed activeEffect
![image](https://github.com/user-attachments/assets/6b335155-5175-4f57-aad0-fc2aa25efb14)

**Comment by Larkinabout** [comment]
I think I'll just split out the tooltip to its own journal entry page as it looks like active effects aren't set up to read the tooltip instead of the journal entry page's main content. Look out for it in the next release.

**Comment by Stonedtroll** [comment]
I don't think it reads either one. I had information in both the main and tooltip section but it still came up blank. See #128.

**Comment by Larkinabout** [comment]
I'm not seeing this issue with dnd5e 4.1.1 and Custom D&D 5e 1.2.0. Please recheck and let me know if it's still an issue.

**Comment by Larkinabout** [comment]
Also, the tooltip issue is fixed in 1.2.0.

**Comment by Stonedtroll** [comment]
FYI: It is working for me. In a sandbox with no other mods running and also in my regular game world with other mods running.

![image](https://github.com/user-attachments/assets/7adbd19d-fa1f-4ce7-957c-96f5a58cc9d2)

**Comment by Stonedtroll** [comment]
I am getting this issue again with version 1.2.2.

**Comment by Larkinabout** [comment]
Hopefully fixed in 1.2.3.
