### ISSUE TITLE
[BUG] Scrolling status textappears two times

### ISSUE THREAD

**Issue by MrFlaig** [Larkinabout/fvtt-custom-dnd5e#135]
**Describe the bug**

Scrolling Status Text appears two times when applying damage or healing.

![image](https://github.com/user-attachments/assets/fe9422cb-7cf0-46c6-94c7-441ee26894a3)

**Module Data**

[custom-dnd5e.json](https://github.com/user-attachments/files/17622938/custom-dnd5e.json)

**Steps to reproduce**
Adjust the Health of a Token via Token Hud or damage trays. It sometimes works on the first try, so do it multiple times.

**Versions:**
- Module: 1.1.2
- System: dnd5e 4.0.4
- Foundry VTT: 12.331
- Browser: Brave v1.71.121 & Chrome 130.0.6723.92
- Tested without any other modules enabled

**Comment by Larkinabout** [comment]
It's a bug with the system: https://github.com/foundryvtt/dnd5e/issues/4485

**Comment by Larkinabout** [comment]
Resolved with dnd5e 4.1+.
