### ISSUE TITLE
[BUG] 1.2.1 Module not working

### ISSUE THREAD

**Issue by MrFlaig** [Larkinabout/fvtt-custom-dnd5e#137]
**Breaking: 1.2.1 is not working**

I get this message with other modules enabled:
![image](https://github.com/user-attachments/assets/c21653b3-d26c-4649-b824-45de63f82fcc)

and this without anything else:
![image](https://github.com/user-attachments/assets/bdaf219b-ea4c-4887-a4ca-d632ce21d16c)

Either way nothing is working and settings are not appearing.

**Steps to reproduce**
1. Install and activate

**Versions:**
- Module: 1.2.1
- System: DnD 4.1
- Foundry VTT: 12.331
- Browser: Chrome

**Comment by Larkinabout** [comment]
Can you export your debug file and include it on this issue please.

**Comment by MrFlaig** [comment]
I think you mean the file from within the configuration of the module? As the settings are not showing up in the configuration menu I can't sorry.

![image](https://github.com/user-attachments/assets/e7d16800-bae9-43e4-bac9-b6ba4fb1deba)

Had everything else deactivated while testing.

**Comment by Stonedtroll** [comment]
Confirm that this is happening. From a sandbox without any other mods:

![image](https://github.com/user-attachments/assets/8bd9bb26-dba0-4caa-833b-1bc4e7e458a0)

Cannot get to settings

![image](https://github.com/user-attachments/assets/1b4c5fd4-ee6d-4434-9eb1-ac9ecfe3d804)

**Comment by Larkinabout** [comment]
Should hopefully be resolved with 1.2.2.

**Comment by MrFlaig** [comment]
Working on my client. Thank you. :)
