### ISSUE TITLE
Bloodied on 'dead' tokens

### ISSUE THREAD

**Issue by godisadj2001** [Larkinabout/fvtt-custom-dnd5e#139]
Hey, I'm not sure if this is a bug or intended behaviour, but if a token is bloodied, and then drops to 0HP they stay 'bloodied' AND dead.

Another token who was perhaps kill in one shot... (e.g. took 7 damage when then had 6 max hp) will NOT be marked as bloodied since it kinda bypassed it.

I get the logic and all, but it kind of looks quite messy and a bit annoying when this happens.

Is it possible to set it so DEAD tokens are NOT also marked as bloodied? - Thanks! :)

![Screenshot 2024-11-17 193821](https://github.com/user-attachments/assets/c0ff0c0d-68f5-49a5-84d0-77b50c769375)

**Comment by Larkinabout** [comment]
Added in 1.2.3.
