### ISSUE TITLE
[BUG] Configure Item Properties adds all properties to Equipment

### ISSUE THREAD

**Issue by DrakosZenuth** [Larkinabout/fvtt-custom-dnd5e#14]
**Describe the bug**
Every single property within the configure item properties has the equipment box checked. Trying to uncheck the boxes and applying the change does not work as all the properties have the boxes checked still.

<img width="599" alt="Item Property Window" src="https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/160396975/5032e335-5b2e-4979-9cb7-3d66b40c2da9">
<img width="562" alt="Resulting Equip Mess" src="https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/160396975/96e256b9-6bd7-433f-8238-20f9b6f8dfd3">

**Steps to reproduce**
1. Go to Configure Item Properties
2. Click on Reset to Default
3. Click save and close
4. Return to Configure Item Properties
5. Uncheck the equipment boxes
6. Click save and close
7. Return to Configure Item Properties
8. See Error

**Versions:**
- Module: [e.g. 0.5.1]
- System: [e.g. dnd5e 3.0.2]
- Foundry VTT: [e.g. 11.315]

**Comment by Larkinabout** [comment]
Try clicking 'Reset to Default' and then click the 'Close' in the top-right rather than 'Save and Close'. It looks like the form is not re-rendering after resetting. It also looks like there is a bug when saving the item properties configuration. I'll have a look.

**Comment by Larkinabout** [comment]
Fixed in 0.5.2.
