### ISSUE TITLE
[BUG] When applying damage through the damage tray from a player created message and "killing" the target, Custom DND5e's util.js setFlag function will trigger a "lacks permission to update" error

### ISSUE THREAD

**Issue by Krigsmaskine** [Larkinabout/fvtt-custom-dnd5e#141]
**Describe the bug**

![image](https://github.com/user-attachments/assets/443cd095-afcd-48ff-9721-eabb7932fa76)

New fresh dnd5e v4.1.1
foundryvtt 12.331

**Module Data**
[custom-dnd5e.json](https://github.com/user-attachments/files/17910049/custom-dnd5e.json)

**Steps to reproduce**
1. Have a user create a damage message (like rolling an Attack activity and clicking the damage button)
2. Apply the damage to a token not owned by the user until it hits 0
3. See error in player's console
It comes in 2 variants, either an actorDelta error or a straight permission missing. I am actually unsure when it differs. If I were to guess as a poor programmer, you need to socket the setFlag to the GM if a flag is needed.

**Versions:**
- Module: 1.2.2
- System: dnd5e v4.1.1
- Foundry VTT: 12.331
- Browser: Chrome for player, Foundry for GM?

**Comment by Larkinabout** [comment]
Fixed in 1.2.3.
