### ISSUE TITLE
[BUG] Can't open item to edit it.

### ISSUE THREAD

**Issue by ctbritt** [Larkinabout/fvtt-custom-dnd5e#148]
**Describe the bug**

Trying to right click on a item on the char sheet (or use the edit button) and the item won't open. 

**Module Data**
[DND 5E Custom.json](https://github.com/user-attachments/files/18041827/DND.5E.Custom.json)

**Steps to reproduce**
1. Right-click or choose the edit menu on an item on the char sheet
2. Click on "Edit"
3. Window doesn't open

**Versions:**
- Module: 1.2.7
- System: dnd5e 4.1.2
- Foundry VTT: 12.331
- Browser: Chromium Engine Version 131.0.6778.86

**Additional context**
![CleanShot 2024-12-06 at 12 51 59](https://github.com/user-attachments/assets/199671a1-8646-4e46-95ab-b11a604e08fa)

**Comment by Larkinabout** [comment]
I think this is from something else adding item properties, which Custom D&D 5e is overriding. For the next release, I've extended the code to support item properties added by other modules/code directly to the config.

**Comment by Larkinabout** [comment]
Hopefully fixed in 1.2.8.
