### ISSUE TITLE
[BUG] "startsWith" error

### ISSUE THREAD

**Issue by YenBenGrey** [Larkinabout/fvtt-custom-dnd5e#149]
**Describe the bug**

When the game loads there is an error in the console that is flagging something called "startsWith" however I have no idea what it is affecting, but I did a FTC and it brought me to this module, I then turned off this module and the errors didn't appear. I will attach a screenshot. 

**Module Data**

Go into the module's settings, open up the Debug Settings menu, click Export Data, save and attach the file here.

**Steps to reproduce**
1. Go to 'Start up the game from scratch'
2. Open Console
3. Scroll down to the error

**Versions:**
- Module: 1.2.7
- System: dnd 4.1.2
- Foundry VTT: 12.331
- Browser: Chrome

**Additional context**

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/77a45974-deb6-4a16-82fc-77516373d5c6" />

[custom-dnd5e.json](https://github.com/user-attachments/files/18267921/custom-dnd5e.json)

**Comment by Larkinabout** [comment]
Fixed in 1.2.8.
