### ISSUE TITLE
[BUG] Missing Checkboxes

### ISSUE THREAD

**Issue by RavenknightDM** [Larkinabout/fvtt-custom-dnd5e#15]
Hi! A big thanks for the module. I have a problem with the checkboxes (magical and weightless) in the new containers being invisible with the last version of custom D&D. Everything is updated but they are simply not there.

Disabling the module returns the boxes.

![Details](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/53635985/19156bcb-29be-40de-a3cc-887e3d088390)

**Comment by Larkinabout** [comment]
Is this on 0.5.2?

**Comment by Larkinabout** [comment]
I've had a look and the issue doesn't seem to be happening on 0.5.2. It may be a carry over from bugs in previous versions. If you open up the 'Configure Item Properties' menu and click 'Reset to Default'. Does this resolve the issue?

**Comment by RavenknightDM** [comment]
Hi! The reset worked just as you said and the check boxes are back. Thanks a lot for everything you do! :)
( And sorry for the bad bug-report, I'm indeed on 0.5.2 )

**Comment by Larkinabout** [comment]
Found the initial cause and fixed in 0.7.3.
