### ISSUE TITLE
[FEATURE] Custom Key Mapping

### ISSUE THREAD

**Issue by MentalReject** [Larkinabout/fvtt-custom-dnd5e#17]
**Describe your idea**
A way to set the key of a counter so you can keep them the same across games. This way Macros and Effects can be used in different games without the need to change anything.

**Comment by Larkinabout** [comment]
I'll look to add a key override in the counter's advanced options as I also like the simplicity of not having to come up with a key.

**Comment by MentalReject** [comment]
That would be wonderful. I love the simplicity of not having to come up with a key for everything too. It's just for some specific things like macros across games that refer to a certain counter. Thank you very much!

**Comment by Larkinabout** [comment]
Added in 0.7.0.
