### ISSUE TITLE
[BUG] Item Feature Attack Action Type Dropdown Blank

### ISSUE THREAD

**Issue by Snailramp** [Larkinabout/fvtt-custom-dnd5e#26]
Item Feature Attack Action Type Dropdown labels are blank.

Occurs with no other modules active 

![Screenshot 2024-02-26 094623](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/85088198/1161b7ea-15d0-4f09-b678-48495e614a25)

**Versions:**
- Module: 0.7.2
- System: DND5e 3.03
- Foundry VTT: 11.315
- Browser: none- Foundry main install

**Comment by Larkinabout** [comment]
You can most likely fix it by opening the Configure Item Action Types menu and clicking Reset to Default. If not, I'll have a look tomorrow and put out a fix.

**Comment by Snailramp** [comment]
You got it, problem solved.  Thank you very much for the quick response!

**Comment by Larkinabout** [comment]
Found the initial caused and fixed in 0.7.3.
