### ISSUE TITLE
[BUG] replaces all base damage with [object Object]

### ISSUE THREAD

**Issue by DreamyNiri** [Larkinabout/fvtt-custom-dnd5e#35]
**Describe the bug**
![damageroll](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/74745974/2e2c2581-1009-4798-8ce8-3ea770152729)
![dae](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/74745974/4dfb72f2-cec5-4215-a4ad-2f581cb3d7b5)
all base dnd damage types are replaced with [object Object] as a name. MidiQoL applies damage normally but the damage name is changed.

**Versions:**
- Module: 0.8.1
- System: dnd5e 2.4.1
- Foundry VTT: 11.315

**Comment by Larkinabout** [comment]
Hi @DreamyNiri,

Go into the module's settings, open Debug Settings and export your data to file and attach it here for me to investigate please.

**Comment by Larkinabout** [comment]
Closing as no response. If this issue still exists, please send a reply.
