### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Diamond-Dan** [Larkinabout/fvtt-custom-dnd5e#39]
**Describe the bug**

A description of the bug and any screenshots.
If you change tokens with a character sheet open and then change them back to another token type with the sheet open  you can break a character sheet by causing an error. Likely because the old character sheet did not change.

**Module Data**
[custom-dnd5e.json](https://github.com/Larkinabout/fvtt-custom-dnd5e/files/14473908/custom-dnd5e.json)

Go into the module's settings, open up the Debug Settings menu, click Export Data, save and attach the file here.

**Steps to reproduce**
1. Create a token
2. open a character sheet
3. modify that state with the character sheet open
4. Then modify the token with the sheet open
5. Then change it back to another token type
6. Then close the character sheet
7. You likely won't be able to reopen it

**Versions:**
- Module: 1.0
- System: [e.g. dnd5e 2.4.1]
- Foundry VTT: V11 stable
- Browser: Firefox

**Additional context**
Any additional context.

**Comment by Diamond-Dan** [comment]
So just an FYI and update, I think it has to do with the unqiue key on stats. This broken ALL of my characters sheets now. Its really unforunate. So i need to remake all of them

**Comment by Diamond-Dan** [comment]
So it seems to have specifically broke AC calculations
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/27791262/bc8c48c4-22d6-4455-a15c-78d592eb57da)

**Comment by Larkinabout** [comment]
What happens if you disable the Custom D&D 5e module. Do your character sheets open?

**Comment by Larkinabout** [comment]
I'll have a proper look in the morning and import your configuration to see what happens. I see you have a Wildjammer AC calculation, though it doesn't look like it was added with Custom D&D 5e?

**Comment by Larkinabout** [comment]
Can you also export and attach one of your broken actors, so I can import it into my world for testing.

**Comment by Larkinabout** [comment]
Hi @Diamond-Dan, go into the module's Debug Settings and use the Import Data option to import this file: 
[diamon-dan-custom-dnd5e.json](https://github.com/Larkinabout/fvtt-custom-dnd5e/files/14479164/diamon-dan-custom-dnd5e.json)

I haven't been able to reproduce the issue following the steps you provided, so if you can, please create a copy of your world and try to reproduce the issue and let me know exactly what you did.

**Comment by Diamond-Dan** [comment]
[fvtt-Actor-frolin-37k9HSPT7pdkg7z0.json](https://github.com/Larkinabout/fvtt-custom-dnd5e/files/14485959/fvtt-Actor-frolin-37k9HSPT7pdkg7z0.json)
[treasure-universe.zip](https://github.com/Larkinabout/fvtt-custom-dnd5e/files/14485985/treasure-universe.zip)

I believe this is a broken actor, I reverted my world and am a little hesitant to break it again.  i attached my world as a zip as well>





> What happens if you disable the Custom D&D 5e module. Do your character sheets open?

The sheets were still broken when I did this. 

oddly this bug also broke one my NPCs at the time also, I kept it around. Is there a way to export the broken Monster npc?

![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/27791262/3c2d6023-430a-4e65-a5e0-669fdcaeb4b3)

**Comment by Larkinabout** [comment]
I've just noticed that the actor is for the dnd5e 2.4.1 system and you also listed that as the system version. The Custom D&D 5e module only supports 3.0.1 and up and it's listed as 3.0.1 minimum, so if you are on 2.4.1, I'm not sure how it let you install and enable it. If so, it would probably explain the issues as the config has changed.

**Comment by Diamond-Dan** [comment]
Ah thats a bummer! Does your old custom counters support the old version?

**Comment by Larkinabout** [comment]
> Ah thats a bummer! Does your old custom counters support the old version?

Yes, though it doesn't support fraction counters.

**Comment by Diamond-Dan** [comment]
maybe I will try an upgrade my world. I didn't before because it completely broke everything. I tried using your old module but it didn't seem to work. It just didn't register the new fields.

**Comment by Larkinabout** [comment]
Closing as related to Custom D&D 5e not supporting pre-dnd5e 3.0.0.
