### ISSUE TITLE
Error after uptade[BUG]

### ISSUE THREAD

**Issue by Tsukishici** [Larkinabout/fvtt-custom-dnd5e#44]
The new manifest provoke a missing 0.9.2 folder of some sort ![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/152090207/f41aa602-a257-4df3-97b7-e0b411093f00)
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/152090207/e941c5cd-9dc8-4375-9da2-da5abee8ea12)

**Comment by Larkinabout** [comment]
Apologies, try updating to 0.10.1.

**Comment by Tsukishici** [comment]
> Apologies, try updating to 0.10.1.

No need to apologize, your work it's excellent and you made a very useful module, thank you for your work!
The update worked like a charm.
