### ISSUE TITLE
[BUG] Disappearance of item and spell components

### ISSUE THREAD

**Issue by Liviu50** [Larkinabout/fvtt-custom-dnd5e#45]
The issue is simple.
Using latests Foundry & Latests Dnd 5e module, try to activate this module and look at your items and spells.
None of them has the components stuff there anymore nor can you see the old ones, they simply disappear which i think its pretty problematic :S.
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/96814785/ba685ad3-ee58-444e-9edd-a10fa1ae740c)

that the before

![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/96814785/0e3fd30b-6684-48bd-87c0-da1e6214e0a3)

this is the after.
as you can see it loses all the "concentration" or "verbal" stuff.
any fix planned? module seems pretty nice and useful in the future ^^

**Comment by Larkinabout** [comment]
Hi @Liviu50, you can reset the configurations affected in the module's settings. It's likely that Item Properties as not registered correctly. I have tested on a brand new world and it has not occurred, so it is likely a strange interaction that hasn't been pinned down. If you're still having trouble, go into the module settings, open the Debug Settings menu and use the Export Data option to attach your file here.

**Comment by Liviu50** [comment]
hmm...ok well i tried it on a newly created world, with no other module present and still had the same issue.
[custom-dnd5e.json](https://github.com/Larkinabout/fvtt-custom-dnd5e/files/14543068/custom-dnd5e.json)
here it is.
on a new fresh world, just created, imported one of the example characters they made (but also created one myself to go for sure).
as soon as i activate the module....everything is gone.
once again the world is new so the only active module is this one.
Also, great work guys, this module can allow for so much customization! awesome :) maybe add some to add custom weapons,armor,tools, etc? just an idea ^^
also ill wait to hear from you about this issue cause its a problem...weird one too.

**Comment by Larkinabout** [comment]
Ok, you can fix it just by going into the Configure Item Properties menu in the module settings and clicking Reset to Default. I'll see if I can try and reproduce the issue on my end, but everything should be good once you've done that reset.

**Comment by Larkinabout** [comment]
Fixed in 0.10.3 for initial load.

**Comment by Liviu50** [comment]
thx a bunch and cheers ^^ keep up the good work, module is pretty useful.
and thx for the fix and everything!
