### ISSUE TITLE
[BUG] Error 'undefined reading ('children')' when Opening Character Sheet

### ISSUE THREAD

**Issue by pikasalt** [Larkinabout/fvtt-custom-dnd5e#5]
**Describe the bug**
Having the module enabled causes character sheets to be unable to open.
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/52518103/bad3257d-a0d1-47c8-8c05-38c9072997d1)

**Steps to reproduce**
1. Have module enabled
2. Attempt to open player character sheet.

**Versions:**
- Module: [0.4.0]
- System: [dnd5e 3.0.1]
- Foundry VTT: [11.315]
- Browser: [Chromium 121.0.6167.161]

**Additional context**
I have tried disabling all modules but this one and libwrapper.

**Comment by pikasalt** [comment]
Re-saving the language config and that seemed to fix it! I did not change any of the modules settings after installing, so maybe the shipped config file is out of date/invalid?

**Comment by Larkinabout** [comment]
I've added an option to export the module's settings and configuration data in 0.5.
