### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Somel1978** [Larkinabout/fvtt-custom-dnd5e#50]
**Custom Skills are not populated**

If you have a Custom Skill independent where its created, inside the module or through for example Rippers system customizer it is not populated into the Character sheet and as such breaking the character,

**Module Data**

[custom-dnd5e.json](https://github.com/Larkinabout/fvtt-custom-dnd5e/files/14575380/custom-dnd5e.json)

**Steps to reproduce**
1. Go to Module settings and create a Custom Skill
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/35574432/7410e67a-8d47-42fc-88ba-2d4d5a6756c6)

2. Open Character Sheet
3. Notice the lack of the skill
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/35574432/99c9e6ed-fbfa-444f-a733-3063a73f53bc)
4. ....

**Versions:**
- Module: [e.g. 0.11.1]
- System: [e.g. dnd5e 3.0.4]
- Foundry VTT: [e.g. 11.315]
- Browser: [e.g. Google Chrome 121.0.6167.161]

**Additional context**
As I Use a few custom skills module is unusable.

**Comment by Larkinabout** [comment]
Disable 'Apply Instant Death' for now. There is a conflict with that and the system adding custom skills.

**Comment by Larkinabout** [comment]
Fixed in 0.11.2.
