### ISSUE TITLE
Languages Disappear [BUG]

### ISSUE THREAD

**Issue by arachnidarcana** [Larkinabout/fvtt-custom-dnd5e#52]
**Describe the bug**

Languages disappear, leaving only a few that don't work - and the languages that do show after I thought I fixed it by entering all the languages again show as random characters after leaving and coming back. It showed the random characters to the players as well.
It might be a possible conflict with polygot? Or perhaps its from me adding languages, or trying to remove one not used in my game?
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/163706032/90bd6ca0-7286-471e-b3e1-de7a668ba670)

**Module Data**
[custom-dnd5e.json](https://github.com/Larkinabout/fvtt-custom-dnd5e/files/14626227/custom-dnd5e.json)

**Comment by Larkinabout** [comment]
Fixed in 0.12.0.
