### ISSUE TITLE
[BUG] Encumbered Condition Doesn't Account for Weight Modifiers

### ISSUE THREAD

**Issue by aprusik** [Larkinabout/fvtt-custom-dnd5e#53]
**Describe the bug**
The weight modifiers only seem to affect the visual encumbrance on the sheet, and not whatever is tracked for applying/unapplying the encumbered condition.

In the screenshot below, I have equipped items set to reduce their weight to 0. You can see the character sheet shows I am below the first encumbrance level as the hempen rope is equipped, but I am still encumbered:
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/29558544/3f0f3c67-d573-445b-9fab-56252c7b6447)

If I unequip the hempen rope, the carry weight goes above the first threshold where I would expect to be encumbered:
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/29558544/fe3c0d0f-e973-4bc5-866f-493f4196fdcd)

If I instead remove the hempen rope, the visual weight stays the same (because it should have been reduced to zero by the modifier) but the encumbrance effect goes away (note the carry weight is the same as screenshot 1)
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/29558544/13b870c0-ac4e-4695-831b-f78edeafeced)

**Module Data**
New world, no other modules installed

[custom-dnd5e.json](https://github.com/Larkinabout/fvtt-custom-dnd5e/files/14629084/custom-dnd5e.json)

**Steps to reproduce**
1. Set Weight Modifiers to 0
2. Set Encumbrance to "Variant Rules" in the System Settings
3. Go to a character sheet that is barely encumbered
4. Equip something that weighs more than the difference between your weight and the first weight threshold.
5. See error

**Versions:**
- Module: 0.11.2
- System: 3.0.4
- Foundry VTT: 11.315
- Browser: Firefox 123.0.1

**Comment by Larkinabout** [comment]
Fixed in 0.12.0.
