### ISSUE TITLE
[BUG] Radial Status Effects confilcts with Monk's Bloodspats

### ISSUE THREAD

**Issue by TrofimSelbs** [Larkinabout/fvtt-custom-dnd5e#56]
**Describe the bug**

Enabling "Radial Status Effects' in module's settings shows libwrapper's error. Error: _libWrapper module Monks Bloodsplats and module Custom D&D Se modify the same Foundryar functionality and are more likely to conflict. (see console)_
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/124184162/4acdfb68-45a0-47e0-85fa-212dbcc9a065)
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/124184162/80876b1f-84bf-4b28-b31a-90e4cd1d8f89)

**Module Data**
[custom-dnd5e.json](https://github.com/Larkinabout/fvtt-custom-dnd5e/files/14771882/custom-dnd5e.json)

**Steps to reproduce**
1. Enable Monk's bloodspats
2. Enable Custom D&D
3. In Custom D&D go to the bottom of the settings and allow Radial status effects
4. Reload the game
**Result:** a yellow warning from libwrapper shows up. Haven't seen any real consequences other than this error. But they may be

**Versions:**
- Module Custom D&D: [0.12.1]
- Module Monk's Bloodspats: [11.12]
- System: [dnd5e 3.1.0]
- Foundry VTT: [11.315]
- Browser: [Google Chrome]

**Additional context**
Not sure if this issue should be addressed to this module or Monk's Bloodpats, as two conflict. I will make an issue thread in both places.

**Comment by TrofimSelbs** [comment]
Tried and it doesn't remove the message for me, unfortunately

**Comment by Larkinabout** [comment]
It looks like it's ultimately because Monk's Bloodsplats is using a MIXED wrapper to stop the dead status effect overlay from applying for NPCs. libWrapper is warning about potential conflicts because the Monk's patch would stop other patched code from running when they occur after. Not if there's a different way to hide the overlay, but it would be for Monk to look into.

**Comment by TrofimSelbs** [comment]
Got it. I created an issue thread on monks as well, so we’ll see. Thank you!
