### ISSUE TITLE
[FEATURE] Custom Item Rarities

### ISSUE THREAD

**Issue by MentalReject** [Larkinabout/fvtt-custom-dnd5e#59]
A way to add additional item rarities and possibly rarity colors to further enhance magical item appearance

**Comment by Larkinabout** [comment]
Seems easy enough to add new item rarities via the config, so I can add a menu for it. Not sure about the colours though as it doesn't look like there's a config for them and they're likely hardcoded in the CSS. Might need a system development, but I'll look into it.

**Comment by Larkinabout** [comment]
Added in 0.12.4.
