### ISSUE TITLE
[BUG] Actor sheet randomly opening for GM/Players

### ISSUE THREAD

**Issue by ItsDrafty** [Larkinabout/fvtt-custom-dnd5e#6]
Hi there,

Kind of confusing to explain but, when a a player or the GM interacts with a character sheet, it will force the sheet to open on the other side. So for instance if delete an item off of a player's sheet, their sheet will open up on their screen even if it wasn't open before. Same thing goes if a player would delete an item, opens on the GM side. It also does this if you change the quantity of a charge or item. 

If a player has limited access, it still pops up for them as well.

I also just noticed if you try to apply a class to a sheet and go through the advancement, it won't let you go past selecting average or rolled hit points.

I can try and elaborate further if needed. Love the module.

Thanks!
Drafty

**Versions:**
- Module: [0.4.0]
- System: [dnd5e 3.0.2]
- Foundry VTT: [e.g. 11.315]
- Browser: [e.g. Google Chrome 121.0.6167.161]

**Comment by Larkinabout** [comment]
Found the issue and it'll be fixed in the next release. Thanks for letting me know!

**Comment by Larkinabout** [comment]
Fixed in 0.5.
