### ISSUE TITLE
[BUG] Error occurs when opening unsupported sheet

### ISSUE THREAD

**Issue by kgar** [Larkinabout/fvtt-custom-dnd5e#62]
**Describe the bug**

When opening a sheet that is not currently included in the `SHEET_TYPE` object in custom dnd5e, errors occur in various hook functions:

![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/4632129/e173b285-2998-434f-86a3-4a1bfdeeae05)

![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/4632129/0df5862b-f602-4f7d-bf91-e584ad981554)

**Module Data**

Go into the module's settings, open up the Debug Settings menu, click Export Data, save and attach the file here.

[custom-dnd5e.json](https://github.com/Larkinabout/fvtt-custom-dnd5e/files/14980387/custom-dnd5e.json)

**Steps to reproduce**
1. Install an unsupported sheet, like Tidy 5e Sheets: https://foundryvtt.com/packages/tidy5e-sheet/ and enable it
2. Open any sheet using the unsupported sheet
3. Note the errors that appear in the devtools console.

**Versions:**
- Module: 0.12.2
- System: dnd5e 3.1.2
- Foundry VTT: 11.315
- Browser: 123.0.6312.122

**Additional context**
Any additional context.

**Comment by Larkinabout** [comment]
Fixed in 0.12.3.
