### ISSUE TITLE
[BUG] Sheet Lags When Multiple People Have Sheet Open

### ISSUE THREAD

**Issue by ItsDrafty** [Larkinabout/fvtt-custom-dnd5e#66]
Hello,

I have noticed for awhile no but haven't pinpointed the issue. When multiple people have a sheet open, it causes the sheet to lag and act weird (scrolling, using a feature, etc). This is frustrating because as the DM, sometimes I need to check character sheets for something while the player has it open. It only does this while I have this module active, with no other modules.

Would this be possible to address? I really want to use the module but this causes so many problems for our table.

Thanks!

Foundry v11
5e v3.1.2.
Module 0.12.3

**Comment by Larkinabout** [comment]
Does it lag with just this module? We use it in our games and I've never noticed any issues with using the character sheet.

**Comment by ItsDrafty** [comment]
Hmmm... maybe it wasn't just with this module installed. It's a really hard error to replicate because I need people connected to try it and that's usually during session and troubleshooting with players who don't understand foundry is tough. I was testing it earlier today logging in as a player and Dm at the same time and sometimes I can replicate and sometimes I can't (using different actors too to test if it's just one character). Sometimes it happens, sometimes it doesn't. But it always seems to happen during session. I don't get any errors in the command console but the sheet becomes buggy and laggy.

I will keep attempting to recreate and isolate the issue.
