### ISSUE TITLE
dnd5e 3.2.0 [Compatibility]

### ISSUE THREAD

**Issue by Tookie03** [Larkinabout/fvtt-custom-dnd5e#67]
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/107572957/54664c16-2e77-4fad-b012-03fef1d2f01c)
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/107572957/41f66888-3ce9-489d-812d-3ad5b0d65fc0)

When reverting back to 3.1.2, module works as intended.

**Versions:**
- Module: [[0.12.3](https://github.com/Larkinabout/fvtt-custom-dnd5e/releases/tag/0.12.3)]
- System: [dnd5e 3.2.0]
- Foundry VTT: [11.315]

**Comment by Larkinabout** [comment]
Added in 0.12.4.
