### ISSUE TITLE
[FEATURE] Foundry v12 Support

### ISSUE THREAD

**Issue by ItsDrafty** [Larkinabout/fvtt-custom-dnd5e#68]
Saw the update to support the D&D 5e system for 3.2, but that requires Foundry v12. When you go to update the module, it states it supports core version 11.315 to function.

**Comment by Larkinabout** [comment]
I've only released a v11 version for dnd5e 3.2.0 so far as I suspect plenty will update the system but not Foundry. Next focus will be on updating all mslodukes for v12.

**Comment by TheTableKnight** [comment]
Sorry to regurgitate the question but is there any updates on when the update to v12 will come out?

**Comment by Larkinabout** [comment]
I'll have a look this week. I was hoping to do some developments before releasing, but those might need to wait until as my time is a limited at the moment.

**Comment by Larkinabout** [comment]
Released with 0.13.0.
