### ISSUE TITLE
Stuck at loading 98% when applying Bloodied in settings [BUG]

### ISSUE THREAD

**Issue by TheLittleJay** [Larkinabout/fvtt-custom-dnd5e#69]
**Describe the bug**

**World gets stuck at loading 98% with this module enabled, if I enable some settings in the [Configure House Rules] section and hit save.** 

No difference if I load as player or DM. Unable to access any other scenes, as foundry says cant switch scenes until current one is finished loading. Unable to disable the module, as if i uncheck it (or any other module for that fact) and try to save, upon reload no changes will be made.

I made a fresh D&D 5e world to troubleshoot / try to replicate this bug, with only this module (and libwrapper) and was able to also get that one stuck at 98%.

![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/54111801/08016c06-b9cb-4a41-a23c-ec327a475ea9)

I use firefox, but if i switch to edge then it loads ok, so it's linked to firefox. 

**Module Data**

[custom-dnd5e.json](https://github.com/user-attachments/files/15539892/custom-dnd5e.json)

**Steps to reproduce**
Enable module (on firefox foundry)
go to [Configure House Rules]
   tick [x] in Apply Bloodied
   tick [x] in Reroll Once
[Save and Close]
upon reload, game is now stuck at 98%

**Versions:**
- Module: [0.12.4]
- System: [dnd5e 3.2.0]
- Foundry VTT: [version 11 stable 315]
- Browser: [Firefox]

**Additional context**

Saw an older comment on the discord about .SVGs and firefox sometimes being funky, if that helps at all....

**Comment by TheLittleJay** [comment]
EDIT:  after some more experimentation, im pretty sure the issue is whatever icon this module is using for the Bloodied condition... 

![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/54111801/e729320f-17e9-426c-a214-7ec4b5869139)

Pic above is the module default, I changed this to a different .svg icon (one from the core D&D 5e system) and the game loaded fine in Firefox. So if you are running firefox, change this icon **before** confirming the bloodied aspect.

**Comment by Larkinabout** [comment]
Fixed in 0.12.5.
