### ISSUE TITLE
[BUG] Currencies do not update and are stuck on default settings

### ISSUE THREAD

**Issue by JeidoUran** [Larkinabout/fvtt-custom-dnd5e#71]
**Describe the bug**

When configuring currencies, specifically their labels and abbreviations, they revert back to the default settings after hitting Save and Close.

**Module Data**

Go into the module's settings, open up the Debug Settings menu, click Export Data, save and attach the file here.
[custom-dnd5e.json](https://github.com/user-attachments/files/15747502/custom-dnd5e.json)

**Steps to reproduce**
1. Go to Configure Currency
2. Edit the Label of a currency
3. Save and Close
4. Re-open Configure Currency
5. The Label will be back to the default one

**Versions:**
- Module: 0.12.6
- System: 3.2.0
- Foundry VTT: 11.315
- Browser: FoundryVTT Desktop

**Additional context**
Any additional context.

**Comment by Larkinabout** [comment]
Fixed in 0.12.7.
