### ISSUE TITLE
[FEATURE] Add flags for "isPhysical" for damage types

### ISSUE THREAD

**Issue by megahead11** [Larkinabout/fvtt-custom-dnd5e#72]
At the moment, it doesn't appear to be possible to flag damage types as "physical" using the custom damage types without manually editing the .json exported from the module settings.

For example, if I were to add a damage type, "ballistic", I couldn't mark it as physical for the purpose of bypasses and midi-qol's DR or resistance flags.

**Comment by Larkinabout** [comment]
Added in 0.13.0 (V12 only). I'll leave this open as I'm planning to do a separate V11 release.

**Comment by Larkinabout** [comment]
Added in 0.12.7.1 (V11 only).
