### ISSUE TITLE
Custom sheet doesn't play nicely with Resources+ [COMPATIBILITY]

### ISSUE THREAD

**Issue by Opius134** [Larkinabout/fvtt-custom-dnd5e#73]
**Describe the bug**

As of right now the Custom sheet has some errors when using the Resources Plus module (https://github.com/ardittristan/5eSheet-resourcesPlus). The resources are presented as favorites, cannot be edited, and cannot be reduced to 0 locally.

Normal behavior from DnD5e 3.0+ sheet
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/100728089/2fe0e886-4adf-4f81-b08a-7407fa92236c)
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/100728089/a29798d8-4d40-4f63-a8af-5ccc0fe70e89)

Behavior from Custom sheet
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/100728089/c3f6b785-5c53-48e3-9bec-24dcb1cc2436)
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/100728089/07cbb0f0-d102-4ba1-9e5a-cd2144b2060a)
![image](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/100728089/abea805e-1d1c-423c-805e-e7d7b1fad47e)

**Module Data**

[custom-dnd5e.json](https://github.com/user-attachments/files/15902769/custom-dnd5e.json)

**Steps to reproduce**
1.Enable both Resources Plus and Custom Dnd5e
2.Change the player actor character sheet type to custom dnd5e
3.The favorites section now has uneditable resources which cannot be hidden by adjusting the setting to 0 resources.

**Versions:**
- Module: Custom D&D 5e v0.12.7, 5e Resources Plus v 1.10.0
- System: dnd5e 3.2.1
- Foundry VTT: V11.315
- Browser: Brave [Version 1.67.116 Chromium: 126.0.6478.71 (Official Build) (64-bit)]

**Comment by Larkinabout** [comment]
My immediate thought is that Resources Plus module just needs to account for the custom sheet's name. The custom sheet is just a slight rejig of the official one, so it'll probably work with all the existing code for the official sheet.

**Comment by Opius134** [comment]
I'll put a bug report over there in that case, thanks for the insight!
