### ISSUE TITLE
[BUG] Can't Open certain config editors with the buttons

### ISSUE THREAD

**Issue by NightmareJoker44** [Larkinabout/fvtt-custom-dnd5e#75]
**The Bug**
Whenever I click on one of the following buttons e.g, Configure Languages, Configure Senses, Configure Item Rarity, Configure Item Activation Cost Types or Configure Item Action Types. I get the below errors that show up in the console via the F12 button.

![image_2024-06-28_130139420](https://github.com/Larkinabout/fvtt-custom-dnd5e/assets/68958277/c29349d9-9145-438b-83a3-e64cb740c417)

**Module Data**
[custom-dnd5e.json](https://github.com/user-attachments/files/16033823/custom-dnd5e.json)

**Steps to reproduce**
1. Go to Configure Game Settings
2. Click on Custom D&D 5e
3. Scroll down to Configure Languages, Configure Senses, Configure Item Rarity, Configure Item Activation Cost Types or Configure Item Action Types.
4. Click on one of the buttons mentioned in step 3
5. Press F12 and go to console tab
6. Look for one of the following Rendering LanguagesForm, Rendering SensesForm, Rendering ItemRarityForm, Rendering ItemActivationCostTypesForm or Rendering ItemActionTypesForm.
7. Then Look at the Error below one of the names mentioned in step 6

**Versions:**
- Module: 0.13.0
- System: dnd5e 3.2.1
- Foundry VTT: ver.12 build 327

**Comment by NightmareJoker44** [comment]
Fixed it was the current world I had but got fixed when I restored the back up.

**Comment by fyre4000** [comment]
I'm having the same issue whenever I try to open the Languages menu. I don't have an older backup to go back to, and I don't want to reset or remake the whole world.
