### ISSUE TITLE
V12 compatible?

### ISSUE THREAD

**Issue by misterio229** [Larkinabout/fvtt-custom-dnd5e#76]
hello, would it be possible to have a version of custom dnd compatible with V12 of foundry VTT

**Comment by Larkinabout** [comment]
The latest release is compatible with V12.

**Comment by Penthious** [comment]
@Larkinabout it's compatible with up to 12.327 but not the latest release which is 12.328.

**Comment by Larkinabout** [comment]
Added in 0.13.1.
