### ISSUE TITLE
[BUG] Adding a Custom Language to a Character/NPC Sheet is adding a lot of unwanted Languages aswell and it doesn't let me remove them

### ISSUE THREAD

**Issue by Juujuubs** [Larkinabout/fvtt-custom-dnd5e#79]
**Describe the bug**
> I added 7 Custom Languages for my campaign, i don't know exactly when this started happening, but i think it was one of the last updates, because before this, it was working normally. Now i can't change choose certain languages in a character sheet and can't change them after i tried to choose one.

So, every time i try to add a language to a character sheet or npc sheet, it adds a lot of languages aswell, and if a try to remove them, it doesn't let me, the only languages i can remove are the custom ones i created. The console doesn't  say anything about it, and any new sheet i try to create, this keeps happening, the only sheets that aren't affected by it are sheets that had their languages set up before this started happening, and if i change a language on them, this happens too

> This happens only with the Custom DnD 5e Module. If keep every module i had active it still happens, and if i deactivate all of them but Libwrapper, Custom DnD 5e and Module Management + and it still persisted.

![image](https://github.com/user-attachments/assets/aa9678fc-108e-4225-905e-42bd6b2e9e7b)

https://github.com/user-attachments/assets/e66c3ed3-9ea6-44f4-94d5-54a414aeb6fd

https://github.com/user-attachments/assets/afe041d5-3998-4671-8f0d-a543859e63b2

**Module Data**

[custom-dnd5e.json](https://github.com/user-attachments/files/16261330/custom-dnd5e.json)

**Steps to reproduce**
> I created at least 7 custom languages
1. Go to a character/npc sheet;
2. Try to add any of the custom languages like you would normally in a sheet;
3. Then it won't let you uncheck many of the languages.

**Versions:**
- Module: 0.13.1
- System: DnD 5e 3.2.1
- Foundry VTT: 12.328
> Using the Foundry Client

**Additional context**
I made many changes using the Custom DnD 5e, like a new Ability, unchecked Electrum in currency, added 3 new types of Damages, added 1 more Item Rarity, added 4 new Senses, added 1 new Skill and added 1 Spell School and setted the Max Level to 21, but all of those are working correctly, just the languages are having this problem.

**Comment by Larkinabout** [comment]
I don't seem to be able to replicate this issue. It might be worth resetting the languages back to the default to see if that resolves the issue.

**Comment by Juujuubs** [comment]
> I don't seem to be able to replicate this issue. It might be worth resetting the languages back to the default to see if that resolves the issue.

That actually does it! Thanks, it might have been some module that i added that added duplicated languages or for some reason when i updated this one it added another set of the same languages, but resetting to default fix it
