### ISSUE TITLE
FVTT V12

### ISSUE THREAD

**Issue by franckflo** [Larkinabout/fvtt-custom-dnd5e#81]
**Describe your idea**
It would be great to have a version of this module compatible with v12

**Comment by megahead11** [comment]
The module *is* compatible with v12, but the maximum version is specified to build 330. 
As far as I'm aware, the module works (from my testing), but to get it to run, may have to right-click, edit the module's  max version in the module screen, as a temp workaround, until the official version is bumped with any necessary adjustments.

**Comment by franckflo** [comment]
Weird, I updated the module.json file to include the version of FVTT that I'm using and uploaded the new module. I was able to see it in the Module Manager and enable it, but the module doesn't seem to work and I don't see its options in the Settings configuration once the world is loaded. It's hosted in Forge, but that shouldn't matter.

**Comment by SetArk** [comment]
Right now, after the update to V12.330 the module just doesn't work anymore because "Core Version is Wrong"

**Comment by Larkinabout** [comment]
Added in 0.13.2.
