### ISSUE TITLE
[FEATURE] Dead or Unconscious on 0 HP

### ISSUE THREAD

**Issue by maxobremer** [Larkinabout/fvtt-custom-dnd5e#84]
**Describe your idea**
It would be nice if this module can make player characters that drop to 0 have the unconscious status effect and/or npc get the dead status effect when they drop to 0 while marking both as defeated for the sake of the combat tracker.

**Versions**
- Module: [e.g. 0.13.3]
- System: [e.g. dnd5e 3.3.1]
- Foundry VTT: [12.330]

**Additional context**
Any additional context.

**Comment by Larkinabout** [comment]
It's on my radar (see #46), just haven't gotten around to it. I'll see if I can sort it for the next release.
