### ISSUE TITLE
[FEATURE] Custom weapon and armor proficiencies

### ISSUE THREAD

**Issue by adriangaro** [Larkinabout/fvtt-custom-dnd5e#86]
**Describe your idea**
Add a way to add custom weapon and armor proficiencies, similar to languages (and their groups).

**Versions**
- Module: [e.g. 0.13.3]
- System: [e.g. dnd5e 3.3.0]
- Foundry VTT: [e.g. 12]

**Comment by Larkinabout** [comment]
It won't be possible to do it exactly the same way as languages as dnd5e uses base items from a compendium to populate the list and also to allocate each base item to a proficiency group (e.g., simple or weapon) via the selected Weapon Type in the item's Details tab. It might need to be one menu to configure the base items and another to map the proficiency to a type.

**Comment by Larkinabout** [comment]
Partially added in 0.14.0. The Configure Armor, Configure Tools and Configure Weapons will allow you to add new base items to the existing groups by pasting the UUID of the item from a compendium you've created. It currently cannot create new groups as that's a little more complicated.

**Comment by sirkerry** [comment]
This would be a great feature, I'd really like the ability to disable the standard base weapons and weapon proficiency groups and replace them with my own base weapons and weapon proficiency groups.

**Comment by Larkinabout** [comment]
Fully added in 0.15.0.
