### ISSUE TITLE
[FEATURE] Roll NPC HP

### ISSUE THREAD

**Issue by Agentblank66** [Larkinabout/fvtt-custom-dnd5e#87]
**Describe your idea**
Adding a way so when a NPC token is created its max hp is rolled based on it hit point formula, so a goblin not always has 7 hit points.
I know JayonKhan had one name "NPCRandomHP" and Moerill had another one name "token-mold".
But none of those work anymore.

**Versions**
- Module: [e.g. 0.13.3]
- System: [e.g. dnd5e 3.3.0]
- Foundry VTT: [e.g. 12]

**Comment by Larkinabout** [comment]
Added in 0.14.0.
