### ISSUE TITLE
[FEATURE] Ability to add Custom Conditions

### ISSUE THREAD

**Issue by Umustalldie2** [Larkinabout/fvtt-custom-dnd5e#88]
**Describe your idea**
Ability to add custom conditions into the conditions hud. 

**Versions**
- Module: [e.g. 1.0.0]
- System: [e.g. dnd5e 3.3.1]
- Foundry VTT: [e.g. 12.330]

**Additional context**
Any additional context.

**Comment by Larkinabout** [comment]
Added in 0.16.0.
