### ISSUE TITLE
[BUG] Temporary HP heals if damage is to small

### ISSUE THREAD

**Issue by maxobremer** [Larkinabout/fvtt-custom-dnd5e#92]
**Describe the bug**
When a creature has temporary hit points and they take damage equal to an amount less then they have temp hp, the creature is healed for the difference in temp hp and damage taken.
![image](https://github.com/user-attachments/assets/aa68878d-1f45-4968-a91d-ba16e0b0ab55)
6hp and 7 temp hp before damage taken

![image](https://github.com/user-attachments/assets/1ba07921-ff5a-4efc-8b03-7e5fe74e5a00)
9hp and 3 temp hp after taking 4 slashing damage

**Module Data**
[Temp HP Bug debug settings custom-dnd5e.json](https://github.com/user-attachments/files/16912874/Temp.HP.Bug.debug.settings.custom-dnd5e.json)

**Steps to reproduce**
1. Have only this module and its requirements enabled
2. give a creature a large number of temp hp and give it less then its maximum hit points
3. roll for damage in chat
4. right click the damage roll and click apply OR use the dnd5e damage application tray
5. check the current hit points

**Versions:**
- Module: [0.14.0]
- System: [ dnd5e 3.3.1]
- Foundry VTT: [12.331]
- Browser: [ my players use firefox and chrome i believe, but happens even without them connected]

**Additional context**
Nice module so far, love the radial status effect option among other things.

**Comment by Larkinabout** [comment]
Fixed in 0.15.0.
