### ISSUE TITLE
[FEATURE] Bring back the death saving throw tracker for players, please

### ISSUE THREAD

**Issue by DragonHale** [Larkinabout/fvtt-custom-dnd5e#94]
Currently, players cannot see nor modify the amount of successes and failures for their saving throws. This is possible within core and I would like to be able to do it again, or at least have a toggle in the module settings so that DMs can choose if their players have access to the core feature or not.
If the toggle/setting exists, I apologize. I have been testing and moving things around for like an hour now and I can't find them. I just don't know where the option might be. Even went testing in an empty world with no modules to see if it was a bug or something and I still don't know if this is a bug or an intentional change :v

**Versions**
- Module: Custom DnD5e 0.14.0
- System: DnD5e 3.3.1
- Foundry VTT: Foundry 12.331

**Additional context**
Here is an image. To the left you can see what the module does to the sheet currently. To the right you see how it it looks in core. The module seems to be hiding the circles for the players (as a DM I can see them with the module enabled). I want the players to be able to see and modify them again.
![image](https://github.com/user-attachments/assets/bf3b6ec5-3317-417f-99e4-03e82ab387ec)

Thanks for the module by the way. I considered disabling it just for this issue, but then realized just how many of the features I use! It is way too important in my games. Great module :)

**Comment by Larkinabout** [comment]
It's a bug. Will be fixed in the next release.

**Comment by Larkinabout** [comment]
Fixed in 0.15.0.
