### ISSUE TITLE
Configuring Proficient & Equipped Item Weight Modifier not functioning

### ISSUE THREAD

**Issue by ChobitsCrazy** [Larkinabout/fvtt-custom-dnd5e#96]
**Describe the bug**

Setting the Proficient & Equipped Item Weight Modifier under the Encumbrance options does not affect the actor's encumbrance when set.
![image](https://github.com/user-attachments/assets/fe7b7e13-6b1a-4e44-94e6-4229323e162d)

Unequipped
![image](https://github.com/user-attachments/assets/e5e89153-af41-4a6b-9ea2-846ad46091a4)

Equipped
![image](https://github.com/user-attachments/assets/b786cf8c-978c-4ae6-9a20-28f142009f1e)

Proficiency
![image](https://github.com/user-attachments/assets/ecd1721d-83e9-477a-8a97-0c566496dfea)
![image](https://github.com/user-attachments/assets/34d19cf8-87ef-4e6f-aff2-1594cc301706)

**Module Data**

Go into the module's settings, open up the Debug Settings menu, click Export Data, save and attach the file here.
[custom-dnd5e.json](https://github.com/user-attachments/files/16967816/custom-dnd5e.json)

**Steps to reproduce**
1. In the Custom D&D Settings set Proficient & Equipped Item Weight Modifier to another value
2. Import Randal from SRD
3. Check weight before and after equipping items.

**Versions:**
- Module: 0.15.0
- System: dnd5e 3.3.1
- Foundry VTT: 12.331
- Browser: Edge

**Comment by Larkinabout** [comment]
Thanks. Looks like the proficiency property changed at some point. Fixed for the next release.
